apiVersion: v1
kind: Namespace
metadata:
  name: guacamole
---
apiVersion: v1
kind: Service
metadata:
  name: guacd
  namespace: guacamole
spec:
  selector:
    app: guacd
  ports:
    - protocol: TCP
      port: 4822
      targetPort: 4822
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: guacamole
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: guacamole
  namespace: guacamole
spec:
  selector:
    app: guacamole
  ports:
    - protocol: TCP
      port: 8080 #itt 80-as port volt
      targetPort: 8080
  type: LoadBalancer #LoadBalancer volt

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacd
  namespace: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacd
  template:
    metadata:
      labels:
        app: guacd
    spec:
      containers:
      - name: guacd
        image: linuxserver/guacd:latest #guacamole/guacd:1.5.4
        volumeMounts:
        - name: drive
          mountPath: /drive
        - name: record
          mountPath: /record
      volumes:
      - name: drive
        hostPath:
          path: /guacamole/drive
      - name: record
        hostPath:
          path: /guacamole/record
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13.4
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/guacamole
        - name: POSTGRES_DB
          value: guacamole_db
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        volumeMounts:
        - name: init
          mountPath: /docker-entrypoint-initdb.d
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: init
        hostPath:
          path: /guacamole/init
      - name: data
        hostPath:
          path: /guacamole/data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
  namespace: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacamole
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      containers:
      - name: guacamole
        image: jwetzell/guacamole:latest #guacamole/guacamole:1.5.4
        env:
        #- name: EXTENSIONS
        #  value: auth-totp
        - name: GUACD_HOSTNAME
          value: guacd
        - name: POSTGRES_DATABASE
          value: guacamole_db
        - name: POSTGRES_HOSTNAME
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRESQL_AUTO_CREATE_ACCOUNTS
          value: "true"
        volumeMounts:
        - name: drive
          mountPath: /drive
      volumes:
      - name: drive
        hostPath:
          path: /guacamole/drive
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: guacamole
type: Opaque
data:
  POSTGRES_USER: Z3VhY2Ftb2xl
  POSTGRES_PASSWORD: Z3VhY2Ftb2xl