apiVersion: apps/v1
kind: Deployment
metadata:
  name: turtlesim-and-teleop
  namespace: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: turtlesim-and-teleop
  template:
    metadata:
      labels:
        app: turtlesim-and-teleop
    spec:
      containers:
      - name: turtlesim-and-teleop
        image: vgergo03/turtlesim-and-teleop:latest
        ports:
        - containerPort: 5902
        env:
        - name: ROS_DOMAIN_ID
          value: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: turtlesim-and-teleop
  namespace: guacamole
spec:
  selector:
    app: turtlesim-and-teleop
  ports:
  - port: 5902
    targetPort: 5902
  type: ClusterIP