apiVersion: apps/v1
kind: Deployment
metadata:
  name: ros2-rqt
  namespace: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ros2-rqt
  template:
    metadata:
      labels:
        app: ros2-rqt
    spec:
      containers:
      - name: ros2-rqt
        image: vgergo03/ros2-rqt-demo:latest
        ports:
        - containerPort: 5900 # VNC port

---
apiVersion: v1
kind: Service
metadata:
  name: ros2-rqt
  namespace: guacamole
spec:
  selector:
    app: ros2-rqt
  ports:
    - protocol: TCP
      port: 5900
      targetPort: 5900
  type: ClusterIP #volt load balancer is itt az előzőben


