apiVersion: apps/v1
kind: Deployment
metadata:
  name: teleop
  namespace: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teleop
  template:
    metadata:
      labels:
        app: teleop
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchFields:
              - key: metadata.name
                operator: In
                values:
                - kind-guac-cluster-worker

      containers:
      - name: teleop
        image: vgergo03/teleop:latest
        tty: true
        stdin: true
        env:
        - name: ROS_DOMAIN_ID
          value: "0"
