apiVersion: apps/v1
kind: Deployment
metadata:
  name: teleop
  namespace: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teleop
  template:
    metadata:
      labels:
        app: teleop
    spec:
      containers:
      - name: teleop
        image: osrf/ros:jazzy-desktop
        tty: true
        stdin: true
        command: ["/bin/bash", "-c", "--"]
        args:
          - |
            apt update && apt install -y ros-jazzy-teleop-twist-keyboard && \
            source /opt/ros/jazzy/setup.bash && \
            ros2 run teleop_twist_keyboard teleop_twist_keyboard --ros-args -r /cmd_vel:=/turtle1/cmd_vel
        env:
        - name: ROS_DOMAIN_ID
          value: "0"
